CC = gcc
CFLAGS = -Wall -Wextra -std=c99

run1:
	$(CC) $(CFLAGS) Question1/student.c Question1/tests.c -o q1
	./q1

run2:
	$(CC) $(CFLAGS) Question2/student.c Question2/tests.c -o q2
	./q2

run3:
	$(CC) $(CFLAGS) Question3/student.c Question3/tests.c -o q3
	./q3

clean:
	rm -f q1 q2 q3